#!/bin/zsh

setdisplay() {
  [[ $1 == a* ]] && pos="--above"
  [[ $1 == b* ]] && pos="--below"
  [[ $1 == l* ]] && pos="--left-of"
  [[ $1 == r* ]] && pos="--right-of"
  [[ $1 == s* ]] && pos="--same-as"

  xrandr --addmode $2 1920x1080
  xrandr --output $2 --mode 1920x1080 $pos eDP1
}

dp() {
  setdisplay $1 DP1
}

hdmi() {
  setdisplay $1 HDMI1
}

brightness() {
  # cat /sys/class/backlight/intel_backlight/max_brightness
  # cat /sys/class/backlight/intel_backlight/actual_brightness
  sudo tee /sys/class/backlight/intel_backlight/brightness <<< $1
}

