#!/bin/zsh

setwallpaper() {
  feh --bg-scale ~/images/wallpaper/arch-pattern.png
  #feh --bg-scale ~/images/wallpaper/arch-wall.png
  #feh --bg-scale ~/images/wallpaper/arch-blue.png
  #feh --bg-scale ~/images/wallpaper/arch-teal.png
  #feh --bg-scale ~/images/wallpaper/arch-grain.png
}

setdisplay() {
  [[ $1 == a* ]] && pos="--above"
  [[ $1 == b* ]] && pos="--below"
  [[ $1 == l* ]] && pos="--left-of"
  [[ $1 == r* ]] && pos="--right-of"
  [[ $1 == s* ]] && pos="--same-as"

  xrandr --addmode $2 1920x1080
  xrandr --output $2 --mode 1920x1080 $pos eDP1
  setwallpaper
}

dp() {
  setdisplay $1 DP1
}

hdmi() {
  setdisplay $1 HDMI2
}

brightness() {
  sudo tee /sys/class/backlight/intel_backlight/brightness <<< $1
  echo "These may prove helpful:"
  echo "cat /sys/class/backlight/intel_backlight/max_brightness"
  echo "cat /sys/class/backlight/intel_backlight/actual_brightness"
}

