#!/bin/zsh

gh() {
  local sock=~/.ssh/github.sock
  rm $sock
  eval $(ssh-agent -s -a $sock)
  ssh-add ~/.ssh/id_github
}

bb() {
  ssh-add ~/.ssh/id_bitbucket
}

gitlab() {
  ssh-add ~/.ssh/id_gitlab
}

digo() {
  ssh-add ~/.ssh/id_digital_ocean
}

ssbpub() {
  ssh-add ~/.ssh/id_ssb_pub
}

