#!/bin/zsh

eval $(keychain --eval --quiet --noask github)

# Shouldn't need the following lines because of the previous line

gh() {
  ssh-add ~/.ssh/github
}

bb() {
  ssh-add ~/.ssh/bitbucket
}

gitlab() {
  ssh-add ~/.ssh/gitlab
}

digo() {
  ssh-add ~/.ssh/digital_ocean
}

ssbpub() {
  ssh-add ~/.ssh/ssb_pub
}

