#!/bin/zsh

kill-ssh-agents() {
  killall ssh-agent
}

gh() {
  kill-ssh-agents
  eval $(ssh-agent -s)
  ssh-add ~/.ssh/id_github
}

bb() {
  kill-ssh-agents
  eval $(ssh-agent -s)
  ssh-add ~/.ssh/bitbucket-hypr
}

gitlab() {
  kill-ssh-agents
  eval $(ssh-agent -s)
  ssh-add ~/.ssh/gitlab
}

digo() {
  kill-ssh-agents
  eval $(ssh-agent -s)
  ssh-add ~/.ssh/digital-ocean
}

ssbpub() {
  kill-ssh-agents
  eval $(ssh-agent -s)
  ssh-add ~/.ssh/ssb-pub
}

