#!/bin/zsh

# The spaceship oh-my-zsh theme
ZSH_THEME="spaceship"
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_DIR_TRUNC=0 # show all
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_DIR_TRUNC_REPO=false

autoload -U promptinit; promptinit
prompt spaceship
